version: "3"

services:
  mysqldb:
    container_name: mysql8
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3309:3309"
    environment:
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - mynetwork
  app:
    depends_on:
      - mysqldb
    image: baherammari/app-spring-repo
    restart: always
    ports:
      - "8089:8089"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql8:3309/devops?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
      MYSQL_HOST: "mysql8"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db:

